language: r

r:
  - release
  - oldrel

sudo: required
dist: xenial
cache:
  - packages
  - ccache

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
    packages:
      - libproj-dev
      - libgeos-dev
      - libgdal-dev

r_packages:
  - rgdal

r_github_packages:
  - r-lib/covr

before_install:
  - echo "ed_un="$ed_un >> ~/.Renviron
  - echo "ed_pw="$ed_pw >> ~/.Renviron

after_success:
- Rscript -e 'library(covr);codecov()'

notifications:
  email:
    on_success: change
    on_failure: change

script:
  - |
    R CMD build .
    travis_wait 20 R CMD check smapr*tar.gz
